package org.example.pathfinder.Controller;

import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.example.pathfinder.Model.LoggedUser;
import org.example.pathfinder.Model.ServiceOffre;
import org.example.pathfinder.Service.ServiceOffreService;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

public class ServiceOffreController {

    @FXML
    private TextField titleField, priceField, requiredExperienceField, requiredEducationField, skillsField;
    @FXML
    private TextArea descriptionField;
    @FXML
    private ComboBox<String> fieldField;
    @FXML
    private ComboBox<String> experienceLevelField;
    @FXML
    private Button submitNewButton, cancelButton;
    @FXML
    private DatePicker dateField;
    @FXML
    private Button writeWithAIButton; // Add this to your FXML

    @FXML
    private DatePicker startDatePicker, endDatePicker;
    @FXML
    private Label durationLabel;

    @FXML
    private ProgressIndicator loadingIndicator; // Add this to your FXML
    @FXML
    private Label aiStatusLabel; // Add this to your FXML

    private LocalDateTime date_posted;
    private final int loggedInUserId =(int) LoggedUser.getInstance().getUserId();
    private final ServiceOffreService serviceOffreService = new ServiceOffreService();
    private ServiceOffre selectedService = null; // Track the selected service for editing

    private static final String API_KEY = "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"; // Replace with your actual API key
    private static final String API_URL = "https://api-inference.huggingface.co/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"; // Model endpoint

    @FXML
    public void initialize() {
        // Initialize field dropdown values
        fieldField.setItems(FXCollections.observableArrayList(
                "Art", "Computer Science", "Engineering", "Accounting", "Business", "Design", "Health"
        ));
        fieldField.setValue(null);

        // Initialize experience level dropdown values
        experienceLevelField.setItems(FXCollections.observableArrayList(
                "Beginner", "Intermediate", "Expert"
        ));
        experienceLevelField.setValue(null);

        // Add listeners to required fields
        titleField.textProperty().addListener((observable, oldValue, newValue) -> checkFieldsAndSuggestPrice());
        fieldField.valueProperty().addListener((observable, oldValue, newValue) -> checkFieldsAndSuggestPrice());
        experienceLevelField.valueProperty().addListener((observable, oldValue, newValue) -> checkFieldsAndSuggestPrice());
        durationLabel.textProperty().addListener((observable, oldValue, newValue) -> checkFieldsAndSuggestPrice());

        // Add focus listener to price field
        priceField.focusedProperty().addListener((observable, oldValue, newValue) -> {
            if (newValue) { // When price field gains focus
                checkFieldsAndSuggestPrice();
            }
        });


        // Calculate duration whenever a date is selected
        startDatePicker.valueProperty().addListener((obs, oldDate, newDate) -> calculateDuration());
        endDatePicker.valueProperty().addListener((obs, oldDate, newDate) -> calculateDuration());



            Tooltip aiTooltip = new Tooltip("This price is generated by AI based on your inputs.");
            priceField.setTooltip(aiTooltip);

        // Ensure descriptionField is empty or has a placeholder
        descriptionField.setText(""); // Clear any pre-populated text
        descriptionField.setPromptText("Enter a professional description..."); // Optional: Set a placeholder
    }

    @FXML
    private void handleSubmit() {
        if (!validateInputs()) return;

        try {

            // Ensure skillsField is not null or empty
            String userEnteredSkills = (skillsField.getText() != null) ? skillsField.getText().trim() : "";
            String extractedSkills = extractSkills(userEnteredSkills); // Extract skills using API

            if (extractedSkills == null || extractedSkills.isEmpty()) {
                extractedSkills = userEnteredSkills; // Fallback to user input if extraction fails
            }

            // Ensure extracted skills are properly formatted (comma-separated)
            extractedSkills = formatSkillsForStorage(extractedSkills);
            if (selectedService != null) {
                selectedService.setTitle(titleField.getText());
                selectedService.setDescription(descriptionField.getText());
                selectedService.setField(fieldField.getValue());
                selectedService.setPrice(Double.parseDouble(priceField.getText()));

                selectedService.setRequired_education(requiredEducationField.getText());
                selectedService.setSkills(extractedSkills); // Store extracted skills
                selectedService.setExperience_level(experienceLevelField.getValue());
                selectedService.setDuration(durationLabel.getText()); // ✅ Set Duration

                serviceOffreService.update(selectedService);
                showAlert("Success", "Service updated successfully!", Alert.AlertType.INFORMATION);
            } else {
                ServiceOffre newService = new ServiceOffre(
                        loggedInUserId, 0, titleField.getText(), descriptionField.getText(),
                        fieldField.getValue(), Double.parseDouble(priceField.getText()),
                         requiredEducationField.getText(),
                        skillsField.getText(), experienceLevelField.getValue(),
                        durationLabel.getText() , "Open"
                );

                serviceOffreService.add(newService);
                showAlert("Success", "Service added successfully!", Alert.AlertType.INFORMATION);
            }

            clearFields();
            closeForm();
        } catch (Exception e) {
            showAlert("Error", "Unexpected error: " + e.getMessage(), Alert.AlertType.ERROR);
        }
    }

    private String formatSkillsForStorage(String skills) {
        if (skills == null || skills.trim().isEmpty()) {
            return "";
        }
        // Remove extra spaces, convert to lowercase, and ensure comma separation
        return skills.replaceAll("\\s*,\\s*", ", ").toLowerCase();
    }


    private void closeForm() {
        Stage stage = (Stage) submitNewButton.getScene().getWindow();
        stage.close();
    }

    public void loadServiceData(ServiceOffre service) {
        if (service == null) {
            System.err.println("❌ Service is NULL in loadServiceData()");
            return;
        }

        System.out.println("📌 Loading Service: " + service.getTitle());
        System.out.println("📌 Date Posted: " + service.getDate_posted().toLocalDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));

        titleField.setText(service.getTitle());
        descriptionField.setText(service.getDescription());
        fieldField.setValue(service.getField());
        priceField.setText(String.valueOf(service.getPrice()));

        requiredEducationField.setText(service.getRequired_education());
        skillsField.setText(service.getSkills());
        experienceLevelField.setValue(service.getExperience_level());
        durationLabel.setText(service.getDuration()); // ✅ Load Duration

        selectedService = service;
    }

    private boolean validateInputs() {
        String errorMessage = "";

        if (experienceLevelField.getValue() == null) {
            errorMessage += "❌ Please select an Experience Level!\n";
        }

        if (durationLabel.getText().equals("Duration: --")) {
            errorMessage += "❌ Please select a start and end date to calculate duration!\n";
        }

        try {
            double price = Double.parseDouble(priceField.getText());
            if (price < 1.0) {
                errorMessage += "❌ Price must be at least 1.0!\n";
            }
        } catch (NumberFormatException e) {
            errorMessage += "❌ Price must be a numeric value!\n";
        }

        if (!errorMessage.isEmpty()) {
            showAlert("Input Validation Error", errorMessage, Alert.AlertType.ERROR);
            return false;
        }
        return true;
    }

    private void clearFields() {
        if (titleField != null) titleField.clear();
        if (descriptionField != null) descriptionField.clear();
        if (fieldField != null) fieldField.setValue(null);
        if (priceField != null) priceField.clear();
        if (requiredEducationField != null) requiredEducationField.clear();
        if (skillsField != null) skillsField.clear();
        if (experienceLevelField != null) experienceLevelField.setValue(null);
        if (durationLabel != null) durationLabel.setText("Duration: --"); // ✅ Clear Duration field
    }


    private void showAlert(String title, String message, Alert.AlertType type) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    // ✅ Method to suggest AI Price
    private void suggestAIPrice() {
        String serviceTitle = titleField.getText();
        String serviceField = fieldField.getValue();
        String experienceLevel = experienceLevelField.getValue();
        String duration = durationLabel.getText().replace("Duration: ", ""); // Extract duration from label

        if (serviceTitle.isEmpty() || serviceField == null || experienceLevel == null || duration.equals("--")) {
            showAlert("Error", "Please enter a service title, select a field, experience level, and duration.", Alert.AlertType.ERROR);
            return;
        }

        // Show loading indicator
        loadingIndicator.setVisible(true);
        aiStatusLabel.setText("Generating AI price...");
        if (loadingIndicator == null) {
            System.err.println("❌ loadingIndicator is null!");
            return;
        }

        double aiEstimatedPrice = generateAIPrice(serviceTitle, serviceField, experienceLevel, duration);
        if (aiEstimatedPrice > 0) {
            priceField.setText(String.valueOf(aiEstimatedPrice)); // ✅ Update priceField with AI-suggested price
        } else {
            showAlert("Error", "Unable to generate a valid price estimation.", Alert.AlertType.ERROR);
        }
    }

    // ✅ Method to generate AI Price using Hugging Face API
    private double generateAIPrice(String serviceTitle, String serviceField, String experienceLevel, String duration) {
        try {
            // ✅ Updated prompt with experience level and duration
            String prompt = "Estimate the average price for a freelance + service titled '" + serviceTitle +
                    "' with an " + experienceLevel + " experience level Return only a number between 50 and 10000.";

            JSONObject requestData = new JSONObject();
            requestData.put("inputs", prompt);

            URL url = new URL(API_URL);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Authorization", "Bearer " + API_KEY);
            connection.setRequestProperty("Content-Type", "application/json");
            connection.setDoOutput(true);

            try (OutputStream os = connection.getOutputStream()) {
                os.write(requestData.toString().getBytes());
                os.flush();
            }

            StringBuilder response = new StringBuilder();
            try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
                String inputLine;
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
            }

            JSONArray responseArray = new JSONArray(response.toString());
            String result = responseArray.getJSONObject(0).getString("generated_text").trim();

            // ✅ Extract the last number in the response
            String[] parts = result.split("\\D+"); // Split by non-digit characters
            String lastNumber = "";

            // Iterate through the parts to find the last number
            for (String part : parts) {
                if (!part.isEmpty()) {
                    lastNumber = part;
                }
            }

            // ✅ Validate the extracted number
            double price = Double.parseDouble(lastNumber);
            if (price >= 50 && price <= 10000) { // Ensure the price is within a reasonable range
                return price;
            } else {
                return 0.0; // Invalid price
            }
        } catch (Exception e) {
            e.printStackTrace();
            showAlert("Error", "Failed to generate AI price: " + e.getMessage(), Alert.AlertType.ERROR);
            return 0.0;
        }
    }

    private void calculateDuration() {
        LocalDate startDate = startDatePicker.getValue();
        LocalDate endDate = endDatePicker.getValue();

        if (startDate != null && endDate != null) {
            long monthsBetween = ChronoUnit.MONTHS.between(startDate, endDate);

            if (monthsBetween < 1) {
                durationLabel.setText("Duration: Less than 1 month");
            } else if (monthsBetween <= 3) {
                durationLabel.setText("Duration: 1-3 months");
            } else if (monthsBetween <= 6) {
                durationLabel.setText("Duration: 3-6 months");
            } else if (monthsBetween <= 12) {
                durationLabel.setText("Duration: 6-12 months");
            } else {
                durationLabel.setText("Duration: More than a year");
            }
        } else {
            durationLabel.setText("Duration: --"); // Reset if dates are not selected
        }
    }


    private void checkFieldsAndSuggestPrice() {
        String serviceTitle = titleField.getText();
        String serviceField = fieldField.getValue();
        String experienceLevel = experienceLevelField.getValue();
        String duration = durationLabel.getText().replace("Duration: ", ""); // Extract duration from label

        if (!serviceTitle.isEmpty() && serviceField != null && experienceLevel != null && !duration.equals("--")) {
            suggestAIPrice();
        }
    }


    private String extractSkills(String inputText) {
        if (inputText == null || inputText.trim().isEmpty()) {
            return "";
        }

        try {
            // Hugging Face API endpoint
            String apiUrl = "https://api-inference.huggingface.co/models/algiraldohe/lm-ner-linkedin-skills-recognition";
            String apiToken = "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"; // Replace with your actual token

            // Create the HTTP connection
            URL url = new URL(apiUrl);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Authorization", "Bearer " + apiToken);
            connection.setRequestProperty("Content-Type", "application/json");
            connection.setDoOutput(true);

            // Create the JSON payload
            String jsonInputString = "{\"inputs\": \"" + inputText + "\"}";

            // Send the request
            try (OutputStream os = connection.getOutputStream()) {
                byte[] input = jsonInputString.getBytes("utf-8");
                os.write(input, 0, input.length);
            }

            // Read the response
            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = in.readLine()) != null) {
                response.append(line);
            }
            in.close();

            // Parse the JSON response
            JSONArray jsonResponse = new JSONArray(response.toString());
            List<String> extractedSkills = new ArrayList<>();

            for (int i = 0; i < jsonResponse.length(); i++) {
                JSONObject entity = jsonResponse.getJSONObject(i);
                String entityType = entity.getString("entity_group");
                String skillName = entity.getString("word");

                // Only extract skills with relevant tags
                if ("SOFT".equals(entityType) || "TECHNOLOGY".equals(entityType)) {
                    extractedSkills.add(skillName.trim());
                }
            }

            return String.join(", ", extractedSkills); // Return as comma-separated values

        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }

    @FXML
    private void handleWriteWithAI() {
        String serviceTitle = titleField.getText();
        if (serviceTitle == null || serviceTitle.trim().isEmpty()) {
            showAlert("Error", "Please enter a service title first!", Alert.AlertType.ERROR);
            return;
        }

        // Show loading indicator
        loadingIndicator.setVisible(true);
        aiStatusLabel.setText("Generating professional description...");

        // Generate the description using AI
        String aiGeneratedDescription = generateAIDescription(serviceTitle);
        if (aiGeneratedDescription != null && !aiGeneratedDescription.isEmpty()) {
            descriptionField.setText(aiGeneratedDescription); // Update the description field with the generated description
        } else {
            showAlert("Error", "Unable to generate a professional description.", Alert.AlertType.ERROR);
        }

        // Hide loading indicator
        loadingIndicator.setVisible(false);
        aiStatusLabel.setText("");
    }

    private String generateAIDescription(String serviceTitle) {
        try {
            String prompt = "Write a compelling job description for a freelance " + serviceTitle +
                    " service. The description should be clear, specific, and directly highlight" +
                    " the skills, experience, and qualities required. The response should be structured as a professional job posting," +
                    " starting with 'I'm looking for' and limited to 4-5 sentences.";

            JSONObject requestData = new JSONObject();
            requestData.put("inputs", prompt);

            URL url = new URL(API_URL);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Authorization", "Bearer " + API_KEY);
            connection.setRequestProperty("Content-Type", "application/json");
            connection.setDoOutput(true);

            try (OutputStream os = connection.getOutputStream()) {
                os.write(requestData.toString().getBytes());
                os.flush();
            }

            StringBuilder response = new StringBuilder();
            try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
                String inputLine;
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
            }

            JSONArray responseArray = new JSONArray(response.toString());
            if (responseArray.length() > 0) {
                JSONObject firstResponse = responseArray.getJSONObject(0);
                if (firstResponse.has("generated_text")) {
                    String generatedText = firstResponse.getString("generated_text").trim();

                    // ✅ Ensure response does not repeat the prompt
                    if (generatedText.toLowerCase().contains(prompt.toLowerCase())) {
                        generatedText = generatedText.replace(prompt, "").trim();
                    }

                    // ✅ Ensure response starts correctly
                    generatedText = formatAIResponse(serviceTitle, generatedText);

                    return generatedText; // ✅ Return cleaned description
                }
            }

            return null; // No valid description generated
        } catch (Exception e) {
            e.printStackTrace();
            showAlert("Error", "Failed to generate AI description: " + e.getMessage(), Alert.AlertType.ERROR);
            return null;
        }
    }


    private String formatAIResponse(String serviceTitle, String aiResponse) {
        if (aiResponse == null || aiResponse.isEmpty()) {
            return "I'm looking for a " + serviceTitle + " expert."; // Fallback response
        }

        // Normalize whitespace
        aiResponse = aiResponse.trim();

        // Remove unwanted AI explanations and reasoning (Anything before the first "I'm looking for")
        int startIndex = aiResponse.toLowerCase().indexOf("i'm looking for");
        if (startIndex != -1) {
            aiResponse = aiResponse.substring(startIndex);
        } else {
            // If "I'm looking for" is not found, use a fallback
            aiResponse = "I'm looking for a " + serviceTitle + " expert.";
        }

        // Remove unnecessary asterisks or formatting artifacts
        aiResponse = aiResponse.replaceAll("\\*{2,}", ""); // Removes ** bold formatting
        aiResponse = aiResponse.replaceAll("<.*?>", ""); // Removes any HTML tags if present

        // Ensure the response is properly formatted and trimmed
        aiResponse = aiResponse.trim();

        return aiResponse;
    }



}